### ISSUE TITLE
Error retrieve data from AEMET

### ISSUE THREAD

**Issue by dave-code-ruiz** [outon/HomeAssistant-AEMET#1]
sep 03 09:29:03 hassbian hass[1221]: 2019-09-03 09:29:03 ERROR (SyncWorker_9) [custom_components.aemet.aemet] Unable to retrieve data from AEMET. HTTPSConnectionPool(host='opendata.aemet.es', port=443): Max retries exceeded with url: /opendata/api/observacion/convencional/todas?api_key=eyJhXXX7meUo (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_ske_dhe', 'dh key too small')])")))
sep 03 09:29:05 hassbian hass[1221]: 2019-09-03 09:29:05 ERROR (MainThread) [homeassistant.components.weather] aemet: Error on device update!

my configuration.yaml:

```
weather:
    platform: aemet
    name: AEMET
    api_key: eyJhbGXXX
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    cache_dir: /home/homeassistant/.homeassistant/aemetcache
```

Don't work for me, i renew my api_key but same error
